#!/usr/bin/env python3
import argparse
import os
from src.converter import Converter
import logging

lg = logging.getLogger()

BASE_PATH = os.getenv('BASE_PATH')
INPUT_FORMAT = os.getenv('INPUT_FORMAT')
OUTPUT_FORMAT = os.getenv('OUTPUT_FORMAT')

if ',' in INPUT_FORMAT:
    INPUT_FORMAT = list(map(lambda x: str(x).strip(), INPUT_FORMAT.split(',')))

if __name__ == '__main__':
    converter = Converter(output_format=OUTPUT_FORMAT)
    converter.run(input_format=INPUT_FORMAT, base_path=BASE_PATH)
    